### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Boltzmachine** [weihaox/BrainHub#3]
```
Traceback (most recent call last):
  File "/root/BrainHub/eval_caption.py", line 277, in <module>
    main()
  File "/root/BrainHub/eval_caption.py", line 213, in main
    image_paths = [os.path.join(args.image_dir, path) for path in os.listdir(args.image_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'caption/images
```

Should it be `caption/test_images` instead? the one extracted by `processing/decode_images.py`

**Comment by weihaox** [comment]
Yes, you can specify the path to the extracted ground truth images as needed.
